[Patmos] Fix environment variables and paths on CMake, Both CMake and Make version upload package regardless if it can pass the benchmark CET suite.

diff --git a/.github/actions/build-cmake-ninja/action.yml b/.github/actions/build-cmake-ninja/action.yml
--- a/.github/actions/build-cmake-ninja/action.yml
+++ b/.github/actions/build-cmake-ninja/action.yml
@@ -41,15 +41,46 @@ inputs:
     required: false
     default: '4'
 
+
+env:
+  # Define base paths first
+  LLVM_PATH: llvm
+  COMPILER_RT_PATH: compiler-rt
+  NEWLIB_PATH: newlib
+  CLANG_PATH: clang
+  LLD_PATH: lld
+  INSTALL_PATH: install
+  CET_TESTS_PATH: patmos-cet-test-suite
+  # Then define composite paths
+  GITHUB_WORKSPACE: ${{ github.workspace }}
+  BUILD_PATH: ${{ env.GITHUB_WORKSPACE }}/${{ env.LLVM_PATH }}/build
+  COMPILER_RT_BUILD_PATH: ${{ env.GITHUB_WORKSPACE }}/${{ env.COMPILER_RT_PATH }}/build
+  NEWLIB_BUILD_PATH: ${{ env.GITHUB_WORKSPACE }}/${{ env.NEWLIB_PATH }}/build
+
+
+
 runs:
   using: "composite"
+
   steps:
+
+    - name: Debug Paths
+      if: inputs.enable-package == 'true'
+      shell: bash
+      run: |
+        echo "GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}"
+        echo "LLVM_PATH: ${{ env.LLVM_PATH }}"
+        echo "BUILD_PATH: ${{ env.BUILD_PATH }}"
+        cd "${{ env.BUILD_PATH }}" && \
+          git rev-parse --is-inside-work-tree || { echo "ERROR: Not inside a git repo!"; exit 1; }
+        
+
     - name: Create build folders
       shell: bash
       run: |
-        mkdir -p $BUILD_PATH
-        mkdir -p $COMPILER_RT_BUILD_PATH
-        mkdir -p $NEWLIB_BUILD_PATH
+        mkdir -p ${{ env.BUILD_PATH }}
+        mkdir -p ${{ env.COMPILER_RT_BUILD_PATH }}
+        mkdir -p ${{ env.NEWLIB_BUILD_PATH }}
 
     - name: Setup ccache
       shell: bash
@@ -72,7 +103,7 @@ runs:
 
     - name: Configure LLVM Build (CMake + Ninja)
       shell: bash
-      working-directory: ${{env.BUILD_PATH}}
+      working-directory: ${{ env.BUILD_PATH }}
       env:
         TARGETS: ${{ inputs.targets }}
         DEFAULT_TARGET: ${{ inputs.default-target }}
@@ -332,19 +363,22 @@ runs:
         fi
 
     - name: Build Package with Ninja
-      working-directory: ${{env.BUILD_PATH}}
+      working-directory: ${{ env.BUILD_PATH }}
       if: inputs.enable-package == 'true'
       shell: bash
       env:
         PARALLELISM: ${{ inputs.parallelism }}
       run: ninja -j $PARALLELISM PatmosPackage
 
-    - name: Install Compiler Binaries
-      working-directory: ${{env.BUILD_PATH}}
-      if: (inputs.enable-package == 'true') && (inputs.enable-tests == 'true')
-      shell: bash
-      run: tar -xvf $(find . -name 'patmos-llvm-*.tar.gz') -C $GITHUB_WORKSPACE/$INSTALL_PATH
+    - name: Upload Package Artifact
+      if: always() && inputs.enable-package == 'true'
+      uses: actions/upload-artifact@v4
+      with:
+        name: patmos-llvm-alpha-${{ github.sha }}-${{ inputs.default-target }}
+        path: ${{ env.BUILD_PATH }}/patmos-unknown-unknown-elf/package-temp/patmos-llvm-*.tar.gz
 
+
+    # Download CET Test Suite - THIS NEEDS TO BE INVESTIGATED AS THIS IS ANCIENT
     - name: Download CET Test Suite
       if: (inputs.enable-package == 'true') && (inputs.enable-tests == 'true')
       env:
@@ -361,11 +395,4 @@ runs:
       shell: bash
       run: |
         $GITHUB_WORKSPACE/$BUILD_PATH/bin/llvm-lit . -v --filter="^(?!((.*/dijkstra.c)|(.*/gsm_dec.c)|(.*/huff_dec.c)|(.*/st.c)|(.*/minver.c)|(.*/cosf.c))).*"
-
-    - name: Upload Package Artifact
-      if: inputs.enable-package == 'true'
-      uses: actions/upload-artifact@v4
-      with:
-        name: ${{inputs.artifact-name}}
-        path: ${{env.BUILD_PATH}}/patmos-unknown-unknown-elf/package-temp/patmos-llvm-*.tar.gz
 
